const questionsList = [
    [ // Chapter 4
    "What is the title of Chapter 4?",
    "Which chapter discusses Nature, Nurture, and Human Diversity?",
    "What are genes?",
    "What percentage of DNA do all humans share with one another?",
    "What can slight variations in genes cause?",
    "What can activate genes?",
    "What is the major issue discussed in the Nature and Nurture slide?",
    "What is the extent of influence debated?",
    "For how many years was nature vs. nurture a major debate?",
    "What is now recognized about the extremes of nature and nurture?",
    "According to the nature side, what determines our behavior?",
    "According to the nurture side, what determines our behavior?",
    "What is the humorous remark about nature vs. nurture?",
    "What is the focus of the purely nature extreme?",
    "What was the prevailing 'scientific' attitude in the U.S. and other countries in the early 1900s?",
    "What did the focus on genetics lead to?",
    "Why was eugenics morally wrong?",
    "What led to a misunderstanding in the purely nature approach?",
    "Why is the purely nature extreme considered just bad science?",
    "Who said 'Men are built, not born...'?",
    "According to John B. Watson's quote, what can be made of a baby?",
    "What are the possibilities of shaping a baby according to Watson?",
    "What is the focus of the purely nurture extreme?",
    "Which groups promoted the purely nurture view?",
    "Who is an example of a behaviorist promoting nurture?",
    "Who is an example of a humanist promoting nurture?",
    "Is the purely nurture view considered good science?",
    "What can the purely nurture extreme lead to?",
    "What book is mentioned in the context of social engineering?",
    "What is the focus of behavioral genetics?",
    "What does behavioral genetics assume about genes and environment?",
    "How does behavioral genetics differ from molecular genetics?",
    "What are adoption studies designed to separate?",
    "What do adoption studies examine?",
    "How many families are required for adoption studies?",
    "What are twin studies designed to compare?",
    "How many twin pairs are required for twin studies?",
    "What do monozygotic twins share?",
    "What do dizygotic twins share?",
    "When identical twins are more alike, what is stronger?",
    "Who studied identical twins reared apart in 1990?",
    "How many sets of identical twins were studied by Bouchard and colleagues?",
    "How similar are identical twins reared apart compared to those raised together?",
    "What are some similarities in identical twins reared apart due to, according to Joseph (2001)?",
    "What is shared environment?",
    "What is the impact of shared environment on personality?",
    "What is nonshared environment?",
    "What are examples of nonshared environment?",
    "How can slight differences in treatment affect siblings?",
    "What are the three types of gene x environment interactions according to Sandra Scarr?",
    "What is the title of Chapter 5?",
    "What do developmental psychologists focus on?",
    "What is the starting point of developmental psychology?",
    "Approximately how many genes are inherited from parents?",
    "What is the end point of developmental psychology?",
    "Why do most people care about child wellbeing?",
    "What are some controversies mentioned related to child wellbeing?",
    "How can the science of developmental psychology help?",
    "What twin studies and epigenetics show about nature and nurture?",
    "What is recognized about the interaction of gene and environment?",
    "What are the two views of the process of development?",
    "What is an example of a trait that changes as we develop?",
    "What is an example of a trait that remains relatively constant?",
    "What are the three major stages of prenatal development?",
    "What can transfer from the mother to the fetus along with nutrients?",
    "What are teratogens?",
    "What types of drugs can impair fetal development?",
    "What else can impair fetal development besides drugs?",
    "What is fetal alcohol syndrome?",
    "What can prenatal alcohol exposure cause?",
    "What is the approximate ratio of children exposed to alcohol who develop fetal alcohol syndrome?",
    "What are pre-programmed reactions right after birth?",
    "What are automatic reflexes?",
    "What is already present in sophisticated thought right after birth?",
    "What are the three types of development discussed in infancy and childhood?",
    "How many nerve cells develop per minute in the womb?",
    "Humans are born with most of their brain cells, approximately how many neurons?",
    "When do brain connections form rapidly?",
    "What becomes increasingly complex as we mature?",
    "From which book is the image of neural networks sourced?",
    "Who published the book Exploring Psychology, 11e?",
    "What is the copyright year of the book mentioned?",
    "What do enriched environments lead to?",
    "The data on enriched environments causing 7%-10% increase in brain weight comes from what?",
    "What is synaptic pruning?",
    "What are critical periods?",
    "What aids learning later in life?",
    "What is neuroplasticity?",
    "When is infants' memory testable?",
    "Who conducted the study involving a mobile and an infant's leg?",
    "What years are associated with Carolyn Rovee-Collier's work?",
    "What was tied from the mobile to the infant's leg?",
    "What did the infant learn in Rovee-Collier's experiment?",
    "What did Rovee-Collier’s work show about infants' memory?",
    "What is infantile amnesia?",
    "What is the average age for the first conscious memory?",
    "Who is primarily associated with the theory of cognitive development stages?",
    "What is cognition?",
    "What serves as the foundation for thought?",
    "What metaphor does Piaget use for children?",
    "Children are naturally what, according to Piaget?",
    "What do children develop to organize information about the world?",
    "What processes do children's theories go through?",
    "When does reorganization occur in Piaget's theory?",
    "What do stages represent in Piaget's theory?",
    "How do stages progress in Piaget's theory?",
    "What is the age range for the sensorimotor stage?",
    "How does the sensorimotor stage begin?",
    "How does the sensorimotor stage end?",
    "What emerges during the sensorimotor stage?",
    "What is the topic of the video linked in the slide?",
    "What is the age range for the preoperational stage?",
    "What do children use in the preoperational stage to represent objects and events?",
    "What is egocentrism in the preoperational stage?",
    "What is animism in the preoperational stage?",
    "What is centration in the preoperational stage?",
    "What problem is mentioned in the preoperational stage slide?",
    "What is the topic of the video linked in the conservation tasks slide?",
    "What do children start to develop in the preoperational stage?",
    "What is theory of mind?",
    "What can children begin to do with theory of mind?",
    "What is the age range for the concrete operational stage?",
    "On what is thinking and problem-solving based in the concrete operational stage?",
    "How is thinking described in the concrete operational stage?",
    "What does thinking become in the concrete operational stage?",
    "What is the focus in the concrete operational stage?",
    "What is the age range for the formal operational stage?",
    "What kind of thinking occurs in the formal operational stage?",
    "What type of reasoning is used in the formal operational stage?",
    "Is Piaget's theory still highly influential?",
    "What is the modern view on the timing of Piaget's stages?",
    "How is development viewed in modern critiques of Piaget?",
    "What is said about the sequence of major milestones in Piaget's theory?",
    "According to Vygotsky, cognitive development is inseparable from what?",
    "What does the Zone of Proximal Development separate?",
    "When does optimal learning occur according to Vygotsky?",
    "What is scaffold learning?"
    ]
];

const answersList = [
    [ // Chapter 4
    ["Nature, Nurture, and Human Diversity", "Human Behavior and Genetics", "Cognitive Development in Children", "Physical Development in Infancy"],
    ["Chapter 3", "Chapter 4", "Chapter 5", "Chapter 6"],
    ["Basic unit of inheritance", "Building blocks of proteins", "Type of cells", "Environmental factors"],
    ["Over 90%", "Over 95%", "Over 99%", "Over 80%"],
    ["Changes in traits", "No effect", "Major diseases only", "Environmental changes"],
    ["Environmental events", "Only genetic factors", "Nothing", "Age"],
    ["Nature and Nurture", "Physical Development", "Cognitive Development", "Socioemotional Development"],
    ["Inheritance/environment", "Only inheritance", "Only environment", "Neither"],
    ["Many years", "Few years", "One year", "No debate"],
    ["Neither extreme makes sense", "Nature is correct", "Nurture is correct", "Both extremes are correct"],
    ["Our genetics", "Our environment", "Our upbringing", "Life experiences"],
    ["Our environment, upbringing, and life experiences", "Our genetics", "Personality traits", "Abilities"],
    ["Either way It's your parents fault", "It's your fault", "It's society's fault", "No one's fault"],
    ["Genetics", "Environment", "Both", "Neither"],
    ["Focus on genetics", "Focus on environment", "Balanced view", "No attitude"],
    ["The rise of eugenics", "The rise of behaviorism", "The rise of humanism", "Nothing"],
    ["Morally wrong", "Morally right", "Neutral", "Not mentioned"],
    ["Misunderstanding of genetics", "Understanding of genetics", "Ignore genetics", "Environmental focus"],
    ["Just bad science", "Good science", "Average science", "No science"],
    ["John B. Watson", "Jean Piaget", "Lev Vygotsky", "Abraham Maslow"],
    ["A builder who climbs and uses hands in constructing buildings", "A thief, a gunman or a dope fiend", "All of the above", "Nothing"],
    ["Almost endless", "Limited", "None", "Only positive"],
    ["Environment", "Genetics", "Both", "Neither"],
    ["Behaviorists", "Humanists", "Both", "Neither"],
    ["J. B. Watson", "Abraham Maslow", "Jean Piaget", "Lev Vygotsky"],
    ["Abraham Maslow", "J. B. Watson", "Carolyn Rovee-Collier", "Myers"],
    ["No, still bad science", "Yes", "Maybe", "Not mentioned"],
    ["Social engineering", "Eugenics", "Neuroplasticity", "Object permanence"],
    ["Brave New World Revisited by Aldous Huxley", "Exploring Psychology", "Behaviorism", "Humanism"],
    ["The study of the relationship between genetic variations and individual traits", "The study of environmental effects", "The study of cognitive development", "The study of socioemotional development"],
    ["Both genes and environment matter", "Only genes matter", "Only environment matters", "Neither matters"],
    ["Most traits studied are polygenic", "Focus on single genes", "Focus on environment only", "Focus on cognition"],
    ["Genes (biological parents) from environment (adoptive parents)", "Genes from cognition", "Environment from genes", "None"],
    ["If child shares traits more closely with biological or adoptive parents", "If child shares traits with siblings", "If child shares traits with peers", "None"],
    ["Hundreds of families", "Few families", "One family", "Thousands of families"],
    ["Concordance rates of a trait for monozygotic and dizygotic twins", "Only monozygotic twins", "Only dizygotic twins", "None"],
    ["Hundreds of twin pairs", "Few twin pairs", "One twin pair", "Thousands of twin pairs"],
    ["100% of genes", "50% of genes", "75% of genes", "25% of genes"],
    ["About 50% of genes", "100% of genes", "75% of genes", "25% of genes"],
    ["Genetic influence", "Environmental influence", "Both", "Neither"],
    ["Bouchard and colleagues", "Jean Piaget", "Lev Vygotsky", "John Watson"],
    ["80 sets", "50 sets", "100 sets", "20 sets"],
    ["Less similar than identical raised together, but more similar than fraternal", "More similar than identical raised together", "Less similar than fraternal", "Identical to fraternal"],
    ["Uncontrolled variables other than genes", "Only genes", "Only environment", "None"],
    ["Factors common among siblings", "Factors unique to individuals", "Both", "Neither"],
    ["No clear impact on personality", "Strong impact on personality", "Moderate impact", "None"],
    ["Differences among siblings", "Similarities among siblings", "Both", "Neither"],
    ["Favoritism, birth order, etc.", "Genetics", "Environment", "Cognition"],
    ["May help magnify our differences", "No effect", "Reduce differences", "None"],
    ["Passive, evocative, active", "Only passive", "Only evocative", "Only active"],
    ["Developing Through the Life Span", "Nature, Nurture, and Human Diversity", "Infancy and Childhood", "Cognitive Development"],
    ["How we develop", "How we learn", "How we behave", "How we grow physically"],
    ["~20,000 genes", "10,000 genes", "50,000 genes", "100,000 genes"],
    ["No strict end point", "At birth", "At 18 years", "At 60 years"],
    ["Most people care about child wellbeing", "Most people care about adult wellbeing", "Most people care about education", "Most people care about work"],
    ["Education, day care, spanking, sleeping styles, etc.", "Only education", "Only day care", "Only spanking"],
    ["Can help guide families and social groups to make healthy choices", "Cannot help", "Helps only families", "Helps only social groups"],
    ["Gene and environment interact", "Only genes matter", "Only environment matters", "Neither"],
    ["Both nature and nurture are important", "Only nature", "Only nurture", "Neither"],
    ["Smooth, slow transitions across time? Sharp changes across separable stages of development?", "Only smooth transitions", "Only sharp changes", "No transitions"],
    ["Cognitive skills", "Personality", "Temperament", "Physical skills"],
    ["Temperament becomes personality", "Cognitive skills", "Physical skills", "Emotional skills"],
    ["Zygote", "Embryo", "Fetus", "All of the above"],
    ["Teratogens", "Only nutrients", "Only oxygen", "Only water"],
    ["Chemicals or other agents that pass through the placenta to the fetus and impair development", "Nutrients", "Oxygen", "Water"],
    ["Prescription, over-the-counter, and illegal drugs", "Only prescription drugs", "Only illegal drugs", "Only over-the-counter drugs"],
    ["Environmental toxins", "Only nutrients", "Only oxygen", "Only water"],
    ["Physical and cognitive impairment due to prenatal alcohol exposure", "Only physical impairment", "Only cognitive impairment", "No impairment"],
    ["Serious harm", "No harm", "Mild harm", "Temporary harm"],
    ["1 in ~700", "1 in ~500", "1 in ~1000", "1 in ~200"],
    ["Pre-programmed reactions and development", "Only reflexes", "Only thought", "None"],
    ["Automatic reflexes", "Pre-programmed reactions", "Sophisticated thought", "None"],
    ["Sophisticated thought already present", "Only reflexes", "Only reactions", "None"],
    ["Physical Development", "Cognitive Development", "Socioemotional Development", "All of the above"],
    ["¼ million", "1 million", "100 thousand", "500 thousand"],
    ["~100 billion neurons", "50 billion", "200 billion", "10 billion"],
    ["After birth", "Before birth", "During birth", "Never"],
    ["Neural networks in the cerebral cortex", "Dendrites", "Synapses", "Neurons"],
    ["Myers/DeWall, Exploring Psychology, 11e", "Watson's Behaviorism", "Vygotsky's Theory", "Piaget's Stages"],
    ["Worth Publishers", "Random House", "Penguin", "xAI"],
    ["2019", "1997", "2025", "1900"],
    ["More dendrite connections", "7%-10% increase in brain weight", "Both", "None"],
    ["Animal studies, not human", "Human studies", "Both", "None"],
    ["Shutting down unused connections", "Adding connections", "No change", "Destroying neurons"],
    ["Optimal period for experiences to shape development", "Periods of crisis", "Adult periods", "None"],
    ["Neuroplasticity", "Synaptic pruning", "Object permanence", "Theory of mind"],
    ["The brain's ability to adapt, reorganize, and change its structure and function", "Ability to forget", "Ability to grow new neurons only", "None"],
    ["Soon after birth", "After 2 years", "After 7 years", "Never"],
    ["Carolyn Rovee-Collier", "Jean Piaget", "Lev Vygotsky", "John Watson"],
    ["1997,1999", "1900,1901", "2019,2020", "1970,1971"],
    ["A string", "A toy", "A bell", "Nothing"],
    ["To kick to make mobile move", "To cry", "To sleep", "To eat"],
    ["Events from the past are remembered", "Over time, they may not recall", "Both", "None"],
    ["Lack of memory for early life events", "Amnesia in adults", "No amnesia", "Memory boost"],
    ["Around 3.5 years", "1 year", "5 years", "10 years"],
    ["Jean Piaget", "Lev Vygotsky", "John Watson", "Abraham Maslow"],
    ["Mental activities associated with thinking, knowing, remembering, and communicating", "Physical activities", "Emotional activities", "Social activities"],
    ["Cognition", "Genes", "Environment", "Nurture"],
    ["Child as scientist", "Child as blank slate", "Child as adult", "Child as animal"],
    ["Curious and create theories", "Lazy", "Ignorant", "Happy"],
    ["Schemas", "Genes", "Neurons", "Memories"],
    ["Assimilation", "Accommodation", "Both", "None"],
    ["When children’s theories are wrong most of the time", "When correct", "Always", "Never"],
    ["Reorganization", "Theories", "Schemas", "Periods"],
    ["In same order across all children – no skipping", "Different orders", "Skipping allowed", "Random"],
    ["Birth to approximately 2 years of age", "2 to 7", "7 to 11", "11 and older"],
    ["With reflexive responding", "With symbols", "With abstract thinking", "With deduction"],
    ["With using symbolic processing", "With reflexive", "With concrete", "With formal"],
    ["Object permanence", "Theory of mind", "Conservation", "Deductive reasoning"],
    ["Object Permanence", "Conservation Tasks", "Three Mountain Problem", "Mobile experiment"],
    ["2 to 7 years", "Birth to 2", "7 to 11", "11+"],
    ["Symbols to represent objects and events but with errors", "Reflexes", "Abstract thinking", "Deductive"],
    ["Difficulty seeing the world from another standpoint", "Seeing from others", "Centration", "Animism"],
    ["Inanimate objects are “lifelike”", "Objects permanent", "Concentration on one aspect", "Predict behavior"],
    ["Concentration of one aspect of a problem", "Difficulty seeing other views", "Lifelike objects", "Theory of mind"],
    ["The Three Mountain Problem", "Mobile problem", "Conservation", "Object permanence"],
    ["Conservation Tasks", "Object Permanence", "Three Mountain", "Memory"],
    ["Theory of mind", "Object permanence", "Deductive reasoning", "Reversible operations"],
    ["Ideas about others’ mental states, beliefs, attitudes, knowledge", "About own mind", "About physical", "About emotions"],
    ["Accurately predict behavior from these assumptions", "Forget events", "Prune synapses", "Adapt brain"],
    ["7 to 11 years", "2-7", "Birth-2", "11+"],
    ["Reversible mental operations", "Symbols with errors", "Reflexes", "Abstract"],
    ["More powerful (useful)", "Weak", "Erroneous", "Hypothetical"],
    ["Systematic", "Random", "Egocentric", "Animistic"],
    ["The real and concrete, not the abstract", "Abstract and hypothetical", "Symbols", "Reflexes"],
    ["11 years and older", "7-11", "2-7", "Birth-2"],
    ["Abstract and hypothetical thinking", "Concrete", "Symbolic with errors", "Reflexive"],
    ["Deductive reasoning to draw appropriate conclusions from facts", "Inductive", "No reasoning", "Centration"],
    ["Yes", "No", "Maybe", "Not mentioned"],
    ["A bit off (underestimated infants and overestimated adolescents)", "Accurate", "Too early", "Too late"],
    ["More continuous than in theory", "Staged", "Discontinuous", "Static"],
    ["Still observed", "Not observed", "Changed", "Ignored"],
    ["Social contexts", "Genetic factors", "Physical development", "Memory"],
    ["What a learner can do on their own and what a learner can do with assistance", "Critical period", "Stage of Piaget", "Amnesia"],
    ["When material is in the sweet spot between too easy and too difficult", "Too easy", "Too difficult", "Any level"],
    ["Temporary support for developing higher levels of thinking", "Permanent support", "No support", "Pruning"]
    ]
];

const answerKeyList = [
    [ // Chapter 4
    "Nature, Nurture, and Human Diversity",
    "Chapter 4",
    "Basic unit of inheritance",
    "Over 99%",
    "Changes in traits",
    "Environmental events",
    "Nature and Nurture",
    "Inheritance/environment",
    "Many years",
    "Neither extreme makes sense",
    "Our genetics",
    "Our environment, upbringing, and life experiences",
    "Either way It's your parents fault",
    "Genetics",
    "Focus on genetics",
    "The rise of eugenics",
    "Morally wrong",
    "Misunderstanding of genetics",
    "Just bad science",
    "John B. Watson",
    "A builder who climbs and uses hands in constructing buildings",
    "Almost endless",
    "Environment",
    "Both",
    "J. B. Watson",
    "Abraham Maslow",
    "No, still bad science",
    "Social engineering",
    "Brave New World Revisited by Aldous Huxley",
    "The study of the relationship between genetic variations and individual traits",
    "Both genes and environment matter",
    "Most traits studied are polygenic",
    "Genes (biological parents) from environment (adoptive parents)",
    "If child shares traits more closely with biological or adoptive parents",
    "Hundreds of families",
    "Concordance rates of a trait for monozygotic and dizygotic twins",
    "Hundreds of twin pairs",
    "100% of genes",
    "About 50% of genes",
    "Genetic influence",
    "Bouchard and colleagues",
    "80 sets",
    "Less similar than identical raised together, but more similar than fraternal",
    "Uncontrolled variables other than genes",
    "Factors common among siblings",
    "No clear impact on personality",
    "Differences among siblings",
    "Favoritism, birth order, etc.",
    "May help magnify our differences",
    "Passive, evocative, active",
    "Developing Through the Life Span",
    "How we develop",
    "~20,000 genes",
    "No strict end point",
    "Most people care about child wellbeing",
    "Education, day care, spanking, sleeping styles, etc.",
    "Can help guide families and social groups to make healthy choices",
    "Gene and environment interact",
    "Both nature and nurture are important",
    "Smooth, slow transitions across time? Sharp changes across separable stages of development?",
    "Cognitive skills",
    "Temperament becomes personality",
    "All of the above",
    "Teratogens",
    "Chemicals or other agents that pass through the placenta to the fetus and impair development",
    "Prescription, over-the-counter, and illegal drugs",
    "Environmental toxins",
    "Physical and cognitive impairment due to prenatal alcohol exposure",
    "Serious harm",
    "1 in ~700",
    "Pre-programmed reactions and development",
    "Automatic reflexes",
    "Sophisticated thought already present",
    "All of the above",
    "¼ million",
    "~100 billion neurons",
    "After birth",
    "Neural networks in the cerebral cortex",
    "Myers/DeWall, Exploring Psychology, 11e",
    "Worth Publishers",
    "2019",
    "Both",
    "Animal studies, not human",
    "Shutting down unused connections",
    "Optimal period for experiences to shape development",
    "Neuroplasticity",
    "The brain's ability to adapt, reorganize, and change its structure and function",
    "Soon after birth",
    "Carolyn Rovee-Collier",
    "1997,1999",
    "A string",
    "To kick to make mobile move",
    "Both",
    "Lack of memory for early life events",
    "Around 3.5 years",
    "Jean Piaget",
    "Mental activities associated with thinking, knowing, remembering, and communicating",
    "Cognition",
    "Child as scientist",
    "Curious and create theories",
    "Schemas",
    "Both",
    "When children’s theories are wrong most of the time",
    "Reorganization",
    "In same order across all children – no skipping",
    "Birth to approximately 2 years of age",
    "With reflexive responding",
    "With using symbolic processing",
    "Object permanence",
    "Object Permanence",
    "2 to 7 years",
    "Symbols to represent objects and events but with errors",
    "Difficulty seeing the world from another standpoint",
    "Inanimate objects are “lifelike”",
    "Concentration of one aspect of a problem",
    "The Three Mountain Problem",
    "Conservation Tasks",
    "Theory of mind",
    "Ideas about others’ mental states, beliefs, attitudes, knowledge",
    "Accurately predict behavior from these assumptions",
    "7 to 11 years",
    "Reversible mental operations",
    "More powerful (useful)",
    "Systematic",
    "The real and concrete, not the abstract",
    "11 years and older",
    "Abstract and hypothetical thinking",
    "Deductive reasoning to draw appropriate conclusions from facts",
    "Yes",
    "A bit off (underestimated infants and overestimated adolescents)",
    "More continuous than in theory",
    "Still observed",
    "Social contexts",
    "What a learner can do on their own and what a learner can do with assistance",
    "When material is in the sweet spot between too easy and too difficult",
    "Temporary support for developing higher levels of thinking"
    ]
];

let chaptersList = [
    "Chapter 4"
];

questionsList = [
    "What is the title of Chapter 6?",
    "What is sensation?",
    "What is perception?",
    "What is agnosia?",
    "What is prosopagnosia?",
    "Which part of the brain is damaged in prosopagnosia?",
    "What is bottom-up processing?",
    "What is top-down processing?",
    "What is transduction?",
    "What are the three steps of transduction?",
    "What is the absolute threshold?",
    "What is subliminal stimulation?",
    "What does signal detection theory explain?",
    "How does priming influence detection?",
    "What is the difference threshold?",
    "What is the just noticeable difference (JND)?",
    "What does Weber’s Law state?",
    "What is sensory adaptation?",
    "How does sensory adaptation affect our perception of the world?",
    "What is perceptual set?",
    "How do context effects influence perception?",
    "How do motivation and emotion affect perception?",
    "What is the source of color perception according to the chapter?",
    "What are light waves in terms of color?",
    "What determines the hue of light?",
    "What determines the intensity of light?",
    "What are photoreceptors?",
    "What are the two types of photoreceptors mentioned?",
    "How many rods are in the retina?",
    "What is the function of rods in vision?",
    "How many cones are in the retina?",
    "What is the function of cones in vision?",
    "Where are cones primarily located in the retina?",
    "What are the three kinds of cones?",
    "What is the Young-Helmholtz trichromatic theory?",
    "How does the Young-Helmholtz theory explain colorblindness?",
    "What is Hering’s Opponent-Process Theory?",
    "What are the opponent retinal processes in Hering’s theory?",
    "What causes an afterimage according to Hering’s theory?",
    "What is perceptual organization?",
    "What are the two types of processing involved in perceptual organization?",
    "What is the Gestalt principle of similarity?",
    "What is the Gestalt principle of proximity?",
    "What is the Gestalt principle of good continuation?",
    "What is contour saliency in Gestalt principles?",
    "How does good continuation help in perception?",
    "What is context-dependent perception?",
    "What is perceptual constancy?",
    "What is shape constancy?",
    "What is size constancy?",
    "What is color constancy?",
    "What is unconscious inference according to Helmholtz?",
    "What are saccades?",
    "What is the duration of saccades?",
    "What happens to visual processes during saccades?",
    "What are fixations?",
    "How many saccade-fixation cycles occur per second?"
]

answersList = [
    ["Sensation and Perception", "Color Processing", "Perceptual Organization", "Transduction"],
    ["The reception of stimulation from the environment and its encoding into the nervous system", "The process of interpreting sensory information", "The detection of light waves", "The creation of neural impulses"],
    ["The process of interpreting and understanding sensory information", "The reception of stimulation", "The conversion of energy", "The detection of thresholds"],
    ["Failure or deficit in recognizing objects", "Disruption of face recognition", "Loss of sensory adaptation", "Change in perceptual constancy"],
    ["Disruption of face recognition", "Failure to recognize objects", "Loss of color vision", "Change in sensory thresholds"],
    ["Fusiform gyrus in the ventral stream (‘what’ pathway)", "Occipital lobe", "Parietal lobe", "Temporal lobe"],
    ["Sensory receptors detect stimulus, works up to higher levels of processing", "Use of experience and expectations to draw meaning", "Conversion of energy into neural activity", "Detection of minimum stimulus"],
    ["Use of experience and expectations to draw meaning from stimulus", "Sensory receptors detect stimulus", "Transformation of stimulation", "Delivery of neural info"],
    ["Converting one form of energy into another that our brain can recognize", "Interpreting sensory information", "Detecting stimulus thresholds", "Organizing perceptual data"],
    ["Receive sensory stimulation, Transform that stimulation into neural impulses, Deliver the neural info to the brain", "Detect stimulus, Encode into nervous system, Interpret information", "Convert energy, Process light, Create image", "Receive light, Adapt senses, Perceive color"],
    ["Minimum amount of energy needed to detect a stimulus 50% of the time", "Maximum energy for detection", "Energy below detection", "Energy for difference threshold"],
    ["Below 50% threshold of detection", "Above 50% threshold", "Equal to absolute threshold", "Minimum difference threshold"],
    ["How we detect a stimulus in presence of background information", "How we interpret sensory data", "How we adapt to constant stimulation", "How we organize perceptions"],
    ["Unconscious activation of concepts", "Conscious influence of expectations", "Change in sensory thresholds", "Adaptation to stimulation"],
    ["Minimum difference needed to detect a difference between 2 stimuli", "Maximum difference for detection", "Energy for absolute threshold", "Change in perceptual set"],
    ["Minimum difference needed to detect a difference between 2 stimuli 50% of time", "Maximum detectable difference", "Energy below threshold", "Constant sensory input"],
    ["Detection of difference depends on the percent change", "Depends on absolute difference", "Depends on constant stimulation", "Depends on priming"],
    ["Diminished detection with constant stimulation", "Enhanced detection with change", "Loss of perceptual constancy", "Increase in threshold"],
    ["We see the world as it is important for perception, not as the world is", "We see the world as it appears", "We adapt to all stimuli", "We perceive constant energy"],
    ["Expectations influence perception", "Context changes perception", "Motivation alters perception", "Sensory adaptation occurs"],
    ["The context of the stimulus can change the perceived information", "Expectations influence perception", "Motivation alters perception", "Sensory adaptation occurs"],
    ["Your internal state alters perception of outside events", "Context changes perception", "Expectations influence perception", "Sensory adaptation occurs"],
    ["Color is created in the brain", "Light waves are colored", "Perception is direct", "Cones detect hue"],
    ["Light waves are not colored", "Light waves create color", "Light waves are constant", "Light waves adapt"],
    ["Wavelength", "Amplitude", "Intensity", "Frequency"],
    ["Intensity", "Wavelength", "Hue", "Distance"],
    ["Cells in the retina that detect light", "Neurons in the brain", "Receptors for sound", "Cells for touch"],
    ["Rods and Cones", "Neurons and Cells", "Rods only", "Cones only"],
    ["~120 million", "~60 million", "~6 million", "~200 million"],
    ["Sensitive enough for vision in dark", "Provide color vision", "High acuity", "Detect brightness"],
    ["~6 million", "~120 million", "~60 million", "~200 million"],
    ["Allow color vision", "Vision in dark", "Low acuity", "Detect motion"],
    ["Primarily found in the fovea of the retina", "Spread across the retina", "In the optic nerve", "In the brain"],
    ["Red, Green, Blue", "Yellow, Blue, White", "Red, Yellow, Black", "Green, White, Black"],
    ["Red, green, blue cones provide color perception", "Opponent processes create color", "Cones detect all colors", "Rods provide color"],
    ["Can explain colorblindness", "Cannot explain color perception", "Only explains afterimages", "Only applies to rods"],
    ["Opponent retinal processes explain color perception", "Trichromatic theory of cones", "Rods detect color", "Brain creates all color"],
    ["Red-Green, yellow-blue, white-black", "Red, green, blue", "Yellow, white, black", "Green, blue, white"],
    ["Afterimage results from exhausted color receptors", "Cones create afterimages", "Rods cause afterimages", "Brain suppresses afterimages"],
    ["Piecing the world together", "Interpreting sensory data", "Detecting thresholds", "Adapting to stimuli"],
    ["Bottom-up/top-down processing", "Only bottom-up", "Only top-down", "Sensory adaptation"],
    ["The same-colored dots create a perceived pattern of blue and white rows", "Dots create columns", "Dots form a circle", "No pattern"],
    ["The dots are closer in the columns than in the rows, creating a perception of columns", "Dots form rows", "Dots create a circle", "No perception"],
    ["Line segments are perceptually linked when they are collinear", "Lines form random patterns", "Lines create circles", "No linkage"],
    ["A smooth contour of line elements pops out whereas the jagged contour fades", "Jagged contour pops out", "All contours fade", "No contour effect"],
    ["Good continuation helps us see continuity in objects", "Creates jagged contours", "Fades all objects", "Disrupts perception"],
    ["The four squares indicated by arrows have the same luminance", "Squares have different luminance", "Only two squares match", "No squares match"],
    ["Perceive constant properties of objects even though sensory info changes", "Changes properties with stimuli", "Adapts to constant input", "Ignores properties"],
    ["Perceive constant shape despite angle changes", "Changes shape with angle", "Ignores shape", "Adapts shape"],
    ["Perceive constant size despite distance", "Changes size with distance", "Ignores size", "Adapts size"],
    ["The top surfaces of the cubes—blue on the left and yellow on the right—are the same color", "Cubes have different colors", "Only one color matches", "No color constancy"],
    ["Inference of relationship between distance and size of retinal image", "Direct perception of size", "Constant shape inference", "Color perception"],
    ["Movement one fixation point to another", "Pauses in visual gathering", "Constant visual input", "Neural adaptation"],
    ["25 – 125 ms", "100 – 200 ms", "10 – 50 ms", "200 – 300 ms"],
    ["Suppression of visual processes during saccades", "Enhancement during saccades", "No effect on processes", "Constant processing"],
    ["Pauses where visual information is gathered", "Movements between points", "Constant visual input", "Neural suppression"],
    ["3 to 4", "5 to 6", "1 to 2", "7 to 8"]
]

answerKeyList = [
    "Sensation and Perception",
    "The reception of stimulation from the environment and its encoding into the nervous system",
    "The process of interpreting and understanding sensory information",
    "Failure or deficit in recognizing objects",
    "Disruption of face recognition",
    "Fusiform gyrus in the ventral stream (‘what’ pathway)",
    "Sensory receptors detect stimulus, works up to higher levels of processing",
    "Use of experience and expectations to draw meaning from stimulus",
    "Converting one form of energy into another that our brain can recognize",
    "Receive sensory stimulation, Transform that stimulation into neural impulses, Deliver the neural info to the brain",
    "Minimum amount of energy needed to detect a stimulus 50% of the time",
    "Below 50% threshold of detection",
    "How we detect a stimulus in presence of background information",
    "Unconscious activation of concepts",
    "Minimum difference needed to detect a difference between 2 stimuli",
    "Minimum difference needed to detect a difference between 2 stimuli 50% of time",
    "Detection of difference depends on the percent change",
    "Diminished detection with constant stimulation",
    "We see the world as it is important for perception, not as the world is",
    "Expectations influence perception",
    "The context of the stimulus can change the perceived information",
    "Your internal state alters perception of outside events",
    "Color is created in the brain",
    "Light waves are not colored",
    "Wavelength",
    "Intensity",
    "Cells in the retina that detect light",
    "Rods and Cones",
    "~120 million",
    "Sensitive enough for vision in dark",
    "~6 million",
    "Allow color vision",
    "Primarily found in the fovea of the retina",
    "Red, Green, Blue",
    "Red, green, blue cones provide color perception",
    "Can explain colorblindness",
    "Opponent retinal processes explain color perception",
    "Red-Green, yellow-blue, white-black",
    "Afterimage results from exhausted color receptors",
    "Piecing the world together",
    "Bottom-up/top-down processing",
    "The same-colored dots create a perceived pattern of blue and white rows",
    "The dots are closer in the columns than in the rows, creating a perception of columns",
    "Line segments are perceptually linked when they are collinear",
    "A smooth contour of line elements pops out whereas the jagged contour fades",
    "Good continuation helps us see continuity in objects",
    "The four squares indicated by arrows have the same luminance",
    "Perceive constant properties of objects even though sensory info changes",
    "Perceive constant shape despite angle changes",
    "Perceive constant size despite distance",
    "The top surfaces of the cubes—blue on the left and yellow on the right—are the same color",
    "Inference of relationship between distance and size of retinal image",
    "Movement one fixation point to another",
    "25 – 125 ms",
    "Suppression of visual processes during saccades",
    "Pauses where visual information is gathered",
    "3 to 4"
]

questionsList = [
    "What is the title of Chapter 7?",
    "Who conducted the Little Albert experiment?",
    "What was the conditioned emotional response in the Little Albert experiment?",
    "What did John Watson claim he could do with a dozen healthy infants?",
    "What is learning according to the chapter?",
    "What is a key characteristic of learning?",
    "Which animals are capable of learning?",
    "What is the first step in the learning process?",
    "How do we determine if a stimulus is important?",
    "What is habituation?",
    "What are examples of habituation mentioned?",
    "What type of learning is habituation?",
    "What is associative learning?",
    "What is respondent behavior?",
    "What is classical conditioning?",
    "What is operant conditioning?",
    "Who conducted research on classical conditioning with dogs?",
    "What did Ivan Pavlov study in his experiments?",
    "What is the unconditioned stimulus (US) in Pavlov's experiment?",
    "What is the unconditioned response (UR) in Pavlov's experiment?",
    "What is the neutral stimulus (NS) in Pavlov's experiment?",
    "What happens when the bell is paired with food in Pavlov's experiment?",
    "What becomes the conditioned stimulus (CS) after pairing?",
    "What is the conditioned response (CR) in Pavlov's experiment?",
    "What is acquisition in classical conditioning?",
    "What does acquisition allow in terms of behavior?",
    "What is the neutral stimulus in the computer reboot sound example?",
    "What is the unconditioned stimulus (US) in the computer reboot sound example?",
    "What is the unconditioned response (UR) in the computer reboot sound example?",
    "What is the conditioned stimulus (CS) after acquisition in the computer reboot sound example?",
    "What is the conditioned response (CR) in the computer reboot sound example?",
    "What happens to the conditioned response (CR) after many presentations of CS without US?",
    "What is extinction in classical conditioning?",
    "What happens when CS and US co-occur again after extinction?",
    "What is spontaneous recovery in classical conditioning?",
    "What triggers spontaneous recovery?",
    "Is extinction the same as forgetting?"
]

answersList = [
    ["Learning", "Sensation and Perception", "Color Processing", "Perceptual Organization"],
    ["John Watson", "Ivan Pavlov", "B.F. Skinner", "Jean Piaget"],
    ["Generalization of fear", "Salivation", "Holding out hand", "Reduced response"],
    ["Train them to become any type of specialist", "Teach them basic skills", "Raise them without influence", "Study their natural behavior"],
    ["Acquisition of knowledge, skill, attitudes, or understanding as a result of experience", "Innate behavior change", "Temporary response", "Physical growth"],
    ["Long-lasting change in behavior", "Short-term change", "Immediate reaction", "No change"],
    ["All animals", "Only humans", "Only mammals", "Only birds"],
    ["Begins with detection of a stimulus", "Begins with response", "Begins with habituation", "Begins with association"],
    ["Determine if important or not", "Ignore all stimuli", "Respond to all stimuli", "Adapt to stimuli"],
    ["Ignoring unimportant stimulus", "Responding to all stimuli", "Learning new skills", "Changing behavior"],
    ["Ringing bell at a store/coffee shop, Backup camera warning", "Food presentation", "Bell ringing alone", "Computer reboot"],
    ["Form of Non-Associative Learning", "Associative Learning", "Operant Conditioning", "Classical Conditioning"],
    ["Associative learning happens when two events occur together", "Learning from single events", "Innate response", "Habituation"],
    ["Associate stimuli with automatic response", "Associate response with consequence", "Ignore stimuli", "Adapt to environment"],
    ["Associate a response with its consequence", "Associate stimuli with automatic response", "Reduce response to stimuli", "Learn from experience"],
    ["Ivan Pavlov", "John Watson", "B.F. Skinner", "Lev Vygotsky"],
    ["Work with dogs and study their responses to food", "Study human emotions", "Research operant behavior", "Analyze memory"],
    ["Food", "Bell", "Salivation", "Hand movement"],
    ["Salivation", "Bell ringing", "Food presentation", "Fear response"],
    ["Bell", "Food", "Salivation", "Hand"],
    ["Pairing of bell with food", "Bell alone", "Food alone", "No pairing"],
    ["Bell", "Food", "Salivation", "Hand"],
    ["Salivation", "Fear", "Hand movement", "No response"],
    ["Appearance of conditioned response to the conditioned stimulus", "Reduction of response", "Initial response", "No change"],
    ["Adaptive behavior that allows predictive responses", "Random behavior", "Innate response", "No adaptation"],
    ["Computer Reboot Sound", "Altoid", "Holding out hand", "Salivation"],
    ["Altoid (food)", "Reboot Sound", "Holding out hand", "Salivation"],
    ["Ready to consume Altoid (Holding out hand)", "Reboot Sound", "Salivation", "No response"],
    ["Reboot Sound", "Altoid", "Holding out hand", "Salivation"],
    ["Ready to consume Altoid (Holding out hand)", "Reboot Sound", "Salivation", "No response"],
    ["Weaker CR", "Stronger CR", "No change", "Extinction"],
    ["Presentation of CS without US results in weaker CR", "CS with US strengthens CR", "No effect on CR", "Immediate forgetting"],
    ["CR returns faster than during the initial acquisition", "CR does not return", "CR weakens further", "No change"],
    ["Spontaneous Recovery", "Extinction", "Acquisition", "Habituation"],
    ["After no presentation of CS or US for a while", "Immediate CS presentation", "Continuous US", "No trigger"],
    ["No", "Yes", "Maybe", "Sometimes"]
]

answerKeyList = [
    "Learning",
    "John Watson",
    "Generalization of fear",
    "Train them to become any type of specialist",
    "Acquisition of knowledge, skill, attitudes, or understanding as a result of experience",
    "Long-lasting change in behavior",
    "All animals",
    "Begins with detection of a stimulus",
    "Determine if important or not",
    "Ignoring unimportant stimulus",
    "Ringing bell at a store/coffee shop, Backup camera warning",
    "Form of Non-Associative Learning",
    "Associative learning happens when two events occur together",
    "Associate stimuli with automatic response",
    "Associate a response with its consequence",
    "Ivan Pavlov",
    "Work with dogs and study their responses to food",
    "Food",
    "Salivation",
    "Bell",
    "Pairing of bell with food",
    "Bell",
    "Salivation",
    "Appearance of conditioned response to the conditioned stimulus",
    "Adaptive behavior that allows predictive responses",
    "Computer Reboot Sound",
    "Altoid (food)",
    "Ready to consume Altoid (Holding out hand)",
    "Reboot Sound",
    "Ready to consume Altoid (Holding out hand)",
    "Weaker CR",
    "Presentation of CS without US results in weaker CR",
    "CR returns faster than during the initial acquisition",
    "Spontaneous Recovery",
    "After no presentation of CS or US for a while",
    "No"
]